**Example: Using Two Dense Layers with Specified Weights and Biases.**

In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
# Define inputs as a numpy array (3 samples with 4 features)
inputs = np.array([
    [1, 2, 3, 2.5],
    [2., 5., -1., 2],
    [-1.5, 2.7, 3.3, -0.8]
])


In [3]:
# Step 1: Define the model
# Sequential( )  is a fundamental part of building neural networks using keras.
# keras 
model = Sequential()

# Step 2: Layer 1 - 3 neurons, 4 input features, no activation function
model.add(Dense(3, input_shape=(4,), activation=None))  

# Step 3: Layer 2 - 3 neurons, no activation function
model.add(Dense(3, activation=None))

In [4]:
# Step 4: Set weights and biases for Layer 1
weights1 = np.array([
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]).T  # Transposed to fit Keras' weight shape
biases1 = np.array([2, 3, 0.5])
model.layers[0].set_weights([weights1, biases1])

# Step 5: Set weights and biases for Layer 2
weights2 = np.array([
    [0.1, -0.14, 0.5],
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, -0.13]
]).T  # Transposed to fit Keras' weight shape
biases2 = np.array([-1, 2, -0.5])
model.layers[1].set_weights([weights2, biases2])

In [5]:

# Step 6: Get the output of the network
layer_outputs = model.predict(inputs)
print("Layer 2 Outputs:", layer_outputs)

1/1 [==============================] - 0s 402ms/step
Layer 2 Outputs: [[ 0.50310004 -1.0418501  -2.0387502 ]
 [ 0.2434001  -2.7332     -5.7633004 ]
 [-0.99314004  1.41254    -0.35654998]]


**Explanation of the Example**

1. Model Definition:
   1. A sequential model is defined, and two dense layers are added.
   2. The first dense layer has 3 neurons and accepts 4 input features, with no activation function specified.
   3. The second dense layer also has 3 neurons and no activation function.
1. Setting Weights and Biases:
   1. The weights and biases for each layer are set using the set_weights() method.
   2. The weights are transposed to match the expected shape for Keras, which expects (input_dim, output_dim) for the weights matrix.
   3. The biases are provided as a vector with a length equal to the number of neurons in the layer.

1. Model Prediction:
   1. The model.predict(inputs) method runs a forward pass through the network and outputs the results from the second layer.

**With Dense Layer using own dense layer class**

In [6]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

class Layer_Dense:
    # Layer initialization
    def __init__(self, n_inputs, n_neurons):
        #initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    
    # Forward pass
    def forward(self, inputs):
        # Calculate output values from inputs, weights and biases
        # output_i = (input_i x weight_i) + (input_i x weights_i) + bias_i
        self.output = np.dot(inputs, self.weights) + self.biases


In [34]:
# Create dataset or load dataset
X, y = spiral_data(samples=10, classes=3)

print(X)

[[-0.          0.        ]
 [-0.00368809  0.11104988]
 [ 0.15842274 -0.1558363 ]
 [ 0.24290931 -0.22826777]
 [-0.38173482 -0.22761677]
 [-0.42299822  0.36015895]
 [ 0.01907566  0.6663937 ]
 [ 0.5456464  -0.55426365]
 [ 0.03438422 -0.8882236 ]
 [-0.94407916 -0.32971892]
 [-0.         -0.        ]
 [-0.08640858  0.06985153]
 [-0.0213333   0.22119586]
 [ 0.30461654  0.13535096]
 [ 0.3025599  -0.32555854]
 [ 0.31679606 -0.45637947]
 [-0.4527376  -0.4893599 ]
 [-0.46478483  0.62362915]
 [-0.8536994   0.2476305 ]
 [ 0.9439782  -0.33000776]
 [ 0.          0.        ]
 [ 0.08723553 -0.068816  ]
 [-0.07438628 -0.20940247]
 [-0.24535014 -0.22564223]
 [-0.3377649   0.28886977]
 [ 0.45919636  0.31269905]
 [ 0.5456134  -0.3830802 ]
 [-0.58512723 -0.5124104 ]
 [-0.48534107 -0.74469286]
 [-0.98482966 -0.17352384]]


In [35]:
# Create Dense layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)

In [36]:
# Perform a forward pass of our training data through this layer
dense1.forward(X)

In [38]:
# Let's see output of the first few samples:
print(dense1.output[:5])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 4.4398929e-04 -4.7971696e-07  1.2203632e-03]
 [-1.4110996e-03 -1.5594478e-03 -1.8318458e-03]
 [-2.1227768e-03 -2.3947544e-03 -2.6917229e-03]
 [ 1.0918468e-03  3.9641615e-03 -2.1982705e-03]]


**Without dense layers**

In [ ]:
# Sample inputs, weights, and biases
inputs = [1.0, 2.0]

#Randomly chosen for each connection (2 inputs, 3 neurons)
weights = [
    [0.2, 0.8],  # Weights for Neuron 1
    [-0.5, 0.9], # Weights for Neuron 2
    [0.7, -0.3]  # Weights for Neuron 3
]
biases = [0.5, -1.0, 0.2]

# this code equal to the forward calculates the ouput using 
# np.dot(inputs, self.weights) + self.biases 
# which represents the formula: output=(inputs × weights)+biases
# Manually calculate the outputs
output = [
    inputs[0] * weights[0][0] + inputs[1] * weights[0][1] + biases[0],
    inputs[0] * weights[1][0] + inputs[1] * weights[1][1] + biases[1],
    inputs[0] * weights[2][0] + inputs[1] * weights[2][1] + biases[2]
]

print("Output:", output)  # Expected: [2.3, 0.3, 0.3]
