This code demonstrates each activation function on some sample inputs, allowing you to show how different activations affect the input values.



In [4]:
import numpy as np

class ActivationFunctions:
    @staticmethod
    def linear_activation(x, scale=1.0, bias=0.0):
        # x (float or np.array): Input value or array of values.
        # scale (float): Scaling factor for the input. Defaults to 1.0.
        # bias (float): Bias term added to the input. Defaults to 0.0.
        return scale * x + bias
    
    @staticmethod
    def sigmoid(x):
        return 1 / (1 + np.exp(-x))
    
    @staticmethod
    def tanh(x):
        return np.tanh(x)
    
    @staticmethod
    def relu(x):
        return np.maximum(0, x)
    
    @staticmethod
    def leaky_relu(x, alpha=0.01):
        return np.where(x > 0, x, x * alpha)
    
    @staticmethod
    def softmax(x):
        exp_values = np.exp(x - np.max(x, axis=1, keepdims=True))  # Stability trick
        return exp_values / np.sum(exp_values, axis=1, keepdims=True)

# Example usage:
inputs = np.array([[1, 2, -1], [-1, -2, 0]])
activation = ActivationFunctions()

print("Linear:\n", activation.linear_activation(inputs, scale=2.0, bias=1.0))
print("Sigmoid:\n", activation.sigmoid(inputs))
print("Tanh:\n", activation.tanh(inputs))
print("ReLU:\n", activation.relu(inputs))
print("Leaky ReLU:\n", activation.leaky_relu(inputs))
print("Softmax:\n", activation.softmax(inputs))


Linear:
 [[ 3.  5. -1.]
 [-1. -3.  1.]]
Sigmoid:
 [[0.73105858 0.88079708 0.26894142]
 [0.26894142 0.11920292 0.5       ]]
Tanh:
 [[ 0.76159416  0.96402758 -0.76159416]
 [-0.76159416 -0.96402758  0.        ]]
ReLU:
 [[1 2 0]
 [0 0 0]]
Leaky ReLU:
 [[ 1.    2.   -0.01]
 [-0.01 -0.02  0.  ]]
Softmax:
 [[0.25949646 0.70538451 0.03511903]
 [0.24472847 0.09003057 0.66524096]]
