This code demonstrates each activation function on some sample inputs, allowing you to show how different activations affect the input values.



In [4]:
import numpy as np

class ActivationFunctions:
    @staticmethod
    def linear_activation(x, scale=1.0, bias=0.0):
        # x (float or np.array): Input value or array of values.
        # scale (float): Scaling factor for the input. Defaults to 1.0.
        # bias (float): Bias term added to the input. Defaults to 0.0.
        return scale * x + bias
    
    @staticmethod
    def sigmoid(x):
        return 1 / (1 + np.exp(-x))
    
    @staticmethod
    def tanh(x):
        return np.tanh(x)
    
    @staticmethod
    def relu(x):
        return np.maximum(0, x)
    
    @staticmethod
    def leaky_relu(x, alpha=0.01):
        return np.where(x > 0, x, x * alpha)
    
    @staticmethod
    def softmax(x):
        exp_values = np.exp(x - np.max(x, axis=1, keepdims=True))  # Stability trick
        return exp_values / np.sum(exp_values, axis=1, keepdims=True)

# Example usage:
inputs = np.array([[1, 2, -1], [-1, -2, 0]])
activation = ActivationFunctions()

print("Linear:\n", activation.linear_activation(inputs, scale=2.0, bias=1.0))
print("Sigmoid:\n", activation.sigmoid(inputs))
print("Tanh:\n", activation.tanh(inputs))
print("ReLU:\n", activation.relu(inputs))
print("Leaky ReLU:\n", activation.leaky_relu(inputs))
print("Softmax:\n", activation.softmax(inputs))


Linear:
 [[ 3.  5. -1.]
 [-1. -3.  1.]]
Sigmoid:
 [[0.73105858 0.88079708 0.26894142]
 [0.26894142 0.11920292 0.5       ]]
Tanh:
 [[ 0.76159416  0.96402758 -0.76159416]
 [-0.76159416 -0.96402758  0.        ]]
ReLU:
 [[1 2 0]
 [0 0 0]]
Leaky ReLU:
 [[ 1.    2.   -0.01]
 [-0.01 -0.02  0.  ]]
Softmax:
 [[0.25949646 0.70538451 0.03511903]
 [0.24472847 0.09003057 0.66524096]]


In [8]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

class Layer_Dense:
    # Layer initialization
    def __init__(self, n_inputs, n_neurons):
        #initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    
    # Forward pass
    def forward(self, inputs):
        # Calculate output values from inputs, weights and biases
        # output_i = (input_i x weight_i) + (input_i x weights_i) + bias_i
        self.output = np.dot(inputs, self.weights) + self.biases
    

In [9]:
# ReLU activation
class Activation_ReLU:
    # Forward pass
    def forward(self, inputs):
        # Calculate output values from input
        self.output = np.maximum(0, inputs)

In [14]:
 # Create dataset
 X, y = spiral_data(samples=100, classes=3)
 # Create Dense layer with 2 input features and 3 output values
 dense1 = Layer_Dense(2, 3)
 # Create ReLU activation (to be used with Dense layer):
 activation1 = Activation_ReLU()
 # Make a forward pass of our training data through this layer
 dense1.forward(X)
 print("Before ReLU activation output: \n", dense1.output[:5])
 # Forward pass through activation func.
 # Takes in output from previous layer
 activation1.forward(dense1.output)
 # Let's see output of the first few samples:
 print("After ReLU activation output: \n", activation1.output[:5])

Before ReLU activation output: 
 [[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 1.2344425e-04 -4.2612613e-05  8.7741073e-06]
 [ 2.5981691e-04 -1.5019374e-04  2.1353657e-05]
 [ 4.0532288e-04 -3.3390927e-04  3.8064085e-05]
 [ 5.5259373e-04 -6.4534455e-04  6.0963972e-05]]
After ReLU activation output: 
 [[0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [1.2344425e-04 0.0000000e+00 8.7741073e-06]
 [2.5981691e-04 0.0000000e+00 2.1353657e-05]
 [4.0532288e-04 0.0000000e+00 3.8064085e-05]
 [5.5259373e-04 0.0000000e+00 6.0963972e-05]]


As you can see, negative values have been clipped (modified to be zero). That’s all there is to the 
rectified linear activation function used in the hidden layer.

#### The Softmax Activation Function


In [2]:
# Value from the previous output of NN is
layer_outputs = [4.8, 1.21, 2.385]

# E mathematical constant
E= 2.71828182846

# For each value in a vector, compute the exponential value 
exp_values = [ ] 
for output in layer_outputs:
    exp_values.append(E**output)   # ** is rest to the power
print('Exponentiated values:')
print(exp_values)

Exponentiated values:
[121.51041751893969, 3.3534846525504487, 10.85906266492961]


In [13]:
# Now normalize values 
for i in exp_values:
    print(i,'+')
print('------------------')
norm_base = sum(exp_values) # sum all the values
print(norm_base)

norm_values = []
for value in exp_values:
    norm_values.append(value / norm_base) 
print('\nNormalized exponentiated values:')
print(norm_values)

print('Sum of normalized values:', sum(norm_values))

121.51041751893969 +
3.3534846525504487 +
10.85906266492961 +
------------------
135.72296483641975

Normalized exponentiated values:
[0.8952826639573506, 0.024708306782070668, 0.08000902926057876]
Sum of normalized values: 1.0


the results are similar, but faster to calculate and the code is easier to read with NumPy np.exp(), then np.sum() is faster

In [15]:
import numpy as np
# Values from the earlier previous when we described
# what a neural network is
layer_outputs = [4.8, 1.21, 2.385]
# For each value in a vector, calculate the exponential value
exp_values = np.exp(layer_outputs)
print('exponentiated values:')
print(exp_values)
# Now normalize values
norm_values = exp_values / np.sum(exp_values)
print('normalized exponentiated values:')
print(norm_values)
print('sum of normalized values:', np.sum(norm_values))

exponentiated values:
[121.51041752   3.35348465  10.85906266]
normalized exponentiated values:
[0.89528266 0.02470831 0.08000903]
sum of normalized values: 0.9999999999999999
