In [1]:
# !pip insert numpy
import numpy as np


In [2]:
# storing multiple data types in a array
l_1 = [1,2,3,"4",5.0]
arr_1 = np.array(l_1)
arr_1

array(['1', '2', '3', '4', '5.0'], dtype='<U32')

In [3]:
type(arr_1)

numpy.ndarray

In [4]:
# Data type of array
arr_1.dtype

dtype('<U32')

In [5]:
            # Array size
arr_1.size

5

In [6]:
            # Array shape
arr_1.shape

(5,)

In [17]:
arr_2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2.shape)
arr_2

(2, 4)


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
arr3=np.array(
   [
       [
            [
                [1,2,3,4,5],
                [6,7,8,9,10],
                [6,7,8,9,10]
            ],
            [
                [1,2,3,4,5],
                [6,7,8,9,10],
                [6,7,8,9,10]
            ]
       ],
       
       [
            [
                [1,2,3,4,5],
                [6,7,8,9,10],
                [6,7,8,9,10]
            ],
            [
                [1,2,3,4,5],
                [6,7,8,9,10],
                [6,7,8,9,10]
            ]
       ],
        [
            [
                [1,2,3,4,5],
                [6,7,8,9,10],
                [6,7,8,9,10]
            ],
            [
                [1,2,3,4,5],
                [6,7,8,9,10],
                [6,7,8,9,10]
            ]
       ]
   ]
)

print(arr3.shape)
print(arr3)
print(arr3.ndim)
print(arr3.size)

(3, 2, 3, 5)
[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [ 6  7  8  9 10]]

  [[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [ 6  7  8  9 10]]]


 [[[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [ 6  7  8  9 10]]

  [[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [ 6  7  8  9 10]]]


 [[[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [ 6  7  8  9 10]]

  [[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [ 6  7  8  9 10]]]]
4
90


In [7]:
            # Also array shape
np.shape(arr_1)

(5,)

In [8]:
            # Shows the dimentions of an array
arr_1.ndim

1

In [37]:
            # Fills the entire array with the number '3'
arr123=np.array([1,2,3])
arr123.fill(0)
arr123

array([0, 0, 0])