In [1]:
import numpy as np

In [4]:
            # Initialize a 2D array
m_1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
m_1.ndim 

2

In [4]:
            # shows Shape
m_1.shape

(3, 3)

In [5]:
            # Shows size
m_1.size

9

In [6]:
            # Shows dimentions
m_1.ndim

2

In [7]:
            # Selects a specfic element. Remember, start counting from Zero. [index 0, index 1, index 2,....]
print(m_1)
m_1[2,1]  # [Row,Column]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


8

In [8]:
            # Replacing a specific value
m_1[2,1] = -1
m_1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -1,  9]])

In [20]:
            # Selecting an entire row
m_1[2,1]=8
for i in range(3):
    print("Row ",i,":", m_1[i])

Row  0 : [1 2 3]
Row  1 : [4 5 6]
Row  2 : [7 8 9]


In [27]:
            # Selecting an entire column.
m_1[1:,1]

array([5, 8])

In [36]:
            # Selecting a range
m_1[1,0:1]

array([4])